<template>
  <div class="document-page" v-loading="loading">
    <div class="document-header"><div><el-button link @click="router.push('/inventory/counts')"><el-icon><ArrowLeft /></el-icon> 返回</el-button><h1>库存盘点详情</h1></div><div class="header-actions"><el-button v-if="detail?.status === 'COUNTING'" type="primary" @click="router.push(`/inventory/counts/${id}/edit`)">录入实盘</el-button><el-button v-if="detail?.status === 'APPROVED'" type="success" @click="approve">审核入账</el-button><el-button v-if="detail && !['COMPLETED','CANCELLED'].includes(detail.status)" type="danger" plain @click="cancel">取消盘点</el-button></div></div>
    <el-card class="section-card">
      <template #header><div class="section-title"><span>盘点信息</span><el-tag :type="statusType(detail?.status)">{{ statusLabel(detail?.status) }}</el-tag></div></template>
      <el-descriptions v-if="detail" :column="4" border><el-descriptions-item label="盘点单号">{{ detail.countNo }}</el-descriptions-item><el-descriptions-item label="盘点日期">{{ detail.countDate }}</el-descriptions-item><el-descriptions-item label="盘点仓库">{{ detail.warehouseName }}</el-descriptions-item><el-descriptions-item label="创建时间">{{ detail.createdAt }}</el-descriptions-item><el-descriptions-item label="账面总数">{{ detail.totalBookQuantity }}</el-descriptions-item><el-descriptions-item label="实盘总数">{{ detail.totalActualQuantity }}</el-descriptions-item><el-descriptions-item label="差异总数"><span :class="diffClass(detail.totalDiffQuantity)">{{ signed(detail.totalDiffQuantity) }}</span></el-descriptions-item><el-descriptions-item label="备注">{{ detail.remark || '-' }}</el-descriptions-item></el-descriptions>
    </el-card>
    <el-card class="section-card"><template #header><div class="section-title"><span>盘点明细</span><small>共 {{ detail?.items?.length || 0 }} 项商品</small></div></template><el-table :data="detail?.items || []" border stripe><el-table-column type="index" label="序号" width="60" align="center"/><el-table-column prop="productCode" label="商品编码" width="140"/><el-table-column prop="productName" label="商品名称" min-width="180"/><el-table-column prop="specification" label="规格" min-width="120"/><el-table-column prop="unitName" label="单位" width="80"/><el-table-column prop="bookQuantity" label="账面数量" width="120" align="right"/><el-table-column prop="actualQuantity" label="实盘数量" width="120" align="right"/><el-table-column label="差异" width="110" align="right"><template #default="{ row }"><span :class="diffClass(Number(row.actualQuantity)-Number(row.bookQuantity))">{{ signed(Number(row.actualQuantity)-Number(row.bookQuantity)) }}</span></template></el-table-column><el-table-column prop="reason" label="差异原因" min-width="180"/></el-table></el-card>
  </div>
</template>
<script setup lang="ts">
import { onMounted, ref } from 'vue'; import { useRoute, useRouter } from 'vue-router'; import { ElMessage, ElMessageBox } from 'element-plus'; import { approveInventoryCount, cancelInventoryCount, getInventoryCount } from '@/api/inventory'
const route=useRoute(); const router=useRouter(); const id=Number(route.params.id); const loading=ref(false); const detail=ref<any>(null)
onMounted(load); async function load(){ loading.value=true; try{ detail.value=(await getInventoryCount(id)).data }finally{ loading.value=false } }
function statusLabel(value:string){ return ({DRAFT:'草稿',COUNTING:'盘点中',APPROVED:'待审核',COMPLETED:'已完成',CANCELLED:'已取消'} as any)[value]||value }
function statusType(value:string){ return ({DRAFT:'info',COUNTING:'primary',APPROVED:'warning',COMPLETED:'success',CANCELLED:'danger'} as any)[value]||'' }
function diffClass(value:any){ return Number(value||0)>0?'diff-gain':Number(value||0)<0?'diff-loss':'' } function signed(value:any){const n=Number(value||0);return `${n>0?'+':''}${n.toFixed(4).replace(/\.?0+$/,'')||'0'}`}
async function approve(){await ElMessageBox.confirm('审核后将按差异调整库存，是否继续？','审核入账',{type:'warning'});await approveInventoryCount(id);ElMessage.success('审核入账成功');load()}
async function cancel(){await ElMessageBox.confirm('确定取消该盘点单吗？','取消盘点',{type:'warning'});await cancelInventoryCount(id);ElMessage.success('盘点单已取消');load()}
</script>
<style scoped>
.document-page{padding-bottom:24px}.document-header{min-height:66px;display:flex;align-items:center;justify-content:space-between;margin:-16px -20px 16px;padding:0 22px;background:#fff;border-bottom:1px solid #edf0f5}.document-header>div:first-child,.header-actions,.section-title{display:flex;align-items:center}.document-header>div:first-child{gap:14px}.document-header h1{margin:0;font-size:19px}.header-actions{gap:8px}.section-card+.section-card{margin-top:14px}.section-title{justify-content:space-between;gap:12px}.section-title span{font-size:16px;font-weight:600}.section-title small{color:#a1a8b3}.diff-gain{color:#67c23a;font-weight:600}.diff-loss{color:#f56c6c;font-weight:600}
</style>
