<template>
  <div class="document-page">
    <div class="document-header"><div><el-button link @click="router.back()"><el-icon><ArrowLeft /></el-icon> 返回</el-button><h1>新增{{ title }}</h1></div><div><el-button @click="router.push(basePath)">取消</el-button><el-button type="primary" :loading="submitting" @click="submit">保存草稿</el-button></div></div>
    <el-alert :title="`退货数量不能超过原${sourceLabel}已${isSales ? '出库' : '入库'}且尚未退回的数量。`" type="info" :closable="false" show-icon class="rule-alert" />
    <el-card class="section-card"><template #header><b>基本信息</b></template><el-form label-position="top"><el-row :gutter="20"><el-col :span="8"><el-form-item :label="`原${sourceLabel}`" required><el-select v-model="form.sourceOrderId" filterable style="width:100%" :placeholder="`选择已完成${sourceLabel}`" @change="loadOrder"><el-option v-for="order in orderOptions" :key="order.id" :label="`${order.orderNo} / ${isSales ? order.customerName || '' : order.supplierName || ''}`" :value="order.id" /></el-select></el-form-item></el-col><el-col :span="8"><el-form-item label="退货日期" required><el-date-picker v-model="form.returnDate" type="date" value-format="YYYY-MM-DD" style="width:100%" /></el-form-item></el-col><el-col :span="8"><el-form-item label="退货仓库" required><el-select v-model="form.warehouseId" style="width:100%"><el-option v-for="w in warehouses" :key="w.value" :label="w.label" :value="w.value" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="退货原因"><el-input v-model="form.returnReason" /></el-form-item></el-col><el-col :span="12"><el-form-item label="备注"><el-input v-model="form.remark" /></el-form-item></el-col></el-row></el-form></el-card>
    <el-card class="section-card" v-loading="orderLoading"><template #header><b>退货商品</b></template><el-table :data="form.items" border><el-table-column prop="productCode" label="商品编码" width="125" /><el-table-column prop="productName" label="商品名称" min-width="170" /><el-table-column prop="specification" label="规格" width="120" /><el-table-column prop="unitPrice" label="单价" width="100" align="right" /><el-table-column :prop="isSales ? 'outboundQuantity' : 'inboundQuantity'" :label="isSales ? '已出库' : '已入库'" width="90" align="right" /><el-table-column prop="returnedQuantity" label="已退" width="80" align="right" /><el-table-column prop="maxReturnQuantity" label="可退" width="80" align="right" /><el-table-column label="本次退货" width="150"><template #default="{ row }"><el-input-number v-model="row.returnQuantity" :min="0" :max="row.maxReturnQuantity" :precision="3" style="width:100%" /></template></el-table-column><el-table-column label="退货金额" width="120" align="right"><template #default="{ row }">￥{{ lineAmount(row) }}</template></el-table-column></el-table><el-empty v-if="!form.items.length" description="请选择原业务单据" :image-size="70" /><div class="summary">合计数量：{{ totalQuantity }}　　合计金额：<strong>￥{{ totalAmount }}</strong></div></el-card>
  </div>
</template>
<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'; import { useRoute, useRouter } from 'vue-router'; import { ElMessage } from 'element-plus'; import { createSalesReturn, getSalesOrder, getSalesOrders } from '@/api/sales'; import { createPurchaseReturn, getPurchaseOrder, getPurchaseOrders } from '@/api/purchase'; import { getWarehouseOptions } from '@/api/masterdata'
const route=useRoute(), router=useRouter(); const isSales=computed(()=>route.meta.businessType==='sales'); const title=computed(()=>isSales.value?'销售退货申请':'采购退货申请'); const sourceLabel=computed(()=>isSales.value?'销售单':'采购单'); const basePath=computed(()=>isSales.value?'/sales/returns':'/purchase/returns'); const submitting=ref(false), orderLoading=ref(false), orderOptions=ref<any[]>([]), warehouses=ref<any[]>([]); const form=reactive<any>({sourceOrderId:null,returnDate:new Date().toISOString().slice(0,10),warehouseId:null,returnReason:'',remark:'',items:[]})
const totalQuantity=computed(()=>form.items.reduce((s:number,i:any)=>s+Number(i.returnQuantity||0),0).toFixed(3)); const totalAmount=computed(()=>form.items.reduce((s:number,i:any)=>s+Number(lineAmount(i)),0).toFixed(2))
onMounted(async()=>{const [orders,w]=await Promise.all([isSales.value?getSalesOrders({page:1,size:100,status:'COMPLETED'}):getPurchaseOrders({page:1,size:100,status:'COMPLETED'}),getWarehouseOptions()]);orderOptions.value=orders.data.records||[];warehouses.value=w.data||[]})
async function loadOrder(id:number){if(!id)return;orderLoading.value=true;try{const res=await(isSales.value?getSalesOrder(id):getPurchaseOrder(id));const order=res.data;form.warehouseId=order.warehouseId;form.items=(order.items||[]).map((item:any)=>{const base=Number(isSales.value?item.outboundQuantity:item.inboundQuantity);return{...item,sourceItemId:item.id,maxReturnQuantity:Math.max(0,base-Number(item.returnedQuantity||0)),returnQuantity:0}}).filter((item:any)=>item.maxReturnQuantity>0);if(!form.items.length)ElMessage.warning(`该${sourceLabel.value}没有可退商品`)}finally{orderLoading.value=false}}
async function submit(){const selected=form.items.filter((i:any)=>Number(i.returnQuantity)>0);if(!form.sourceOrderId||!form.returnDate||!form.warehouseId)return ElMessage.warning('请完整填写原单据、退货日期和仓库');if(!selected.length)return ElMessage.warning('请填写至少一项退货数量');const payload:any={returnDate:form.returnDate,warehouseId:form.warehouseId,returnReason:form.returnReason,remark:form.remark,items:selected.map((i:any)=>isSales.value?{salesOrderItemId:i.sourceItemId,quantity:i.returnQuantity}:{purchaseOrderItemId:i.sourceItemId,quantity:i.returnQuantity})};if(isSales.value)payload.salesOrderId=form.sourceOrderId;else payload.purchaseOrderId=form.sourceOrderId;submitting.value=true;try{await(isSales.value?createSalesReturn(payload):createPurchaseReturn(payload));ElMessage.success('退货申请已保存');router.replace(basePath.value)}finally{submitting.value=false}}
function lineAmount(i:any){return(Number(i.returnQuantity||0)*Number(i.unitPrice||0)).toFixed(2)}
</script>
<style scoped>.document-header{min-height:66px;display:flex;align-items:center;justify-content:space-between;margin:-16px -20px 16px;padding:0 22px;background:#fff;border-bottom:1px solid #edf0f5}.document-header>div{display:flex;align-items:center;gap:12px}.document-header h1{margin:0;font-size:19px}.rule-alert{margin-bottom:14px}.section-card+.section-card{margin-top:14px}.summary{margin-top:18px;text-align:right;color:#687386}.summary strong{color:#e66b2f;font-size:19px}</style>
