<template><div class="page-wrapper">
  <el-card><div class="toolbar"><el-input v-model="query.username" placeholder="用户名" clearable style="width:170px"/><el-input v-model="query.realName" placeholder="姓名" clearable style="width:170px"/><el-select v-model="query.status" placeholder="状态" clearable style="width:120px"><el-option label="启用" value="ENABLED"/><el-option label="禁用" value="DISABLED"/></el-select><el-button type="primary" @click="load">查询</el-button><el-button type="success" @click="openAdd">新增员工</el-button></div></el-card>
  <el-card><el-table :data="rows" v-loading="loading" border stripe><el-table-column prop="username" label="用户名" width="120"/><el-table-column prop="realName" label="姓名" width="110"/><el-table-column prop="phone" label="手机号" width="135"/><el-table-column prop="email" label="邮箱" min-width="170"/><el-table-column prop="defaultStoreId" label="默认门店" width="150"><template #default="{row}">{{storeName(row.defaultStoreId)}}</template></el-table-column><el-table-column prop="status" label="状态" width="90"><template #default="{row}"><el-tag :type="row.status==='ENABLED'?'success':'danger'">{{row.status==='ENABLED'?'启用':'禁用'}}</el-tag></template></el-table-column><el-table-column label="操作" width="310" fixed="right"><template #default="{row}"><el-button size="small" @click="openEdit(row)">编辑</el-button><el-button size="small" type="warning" @click="reset(row)">重置密码</el-button><el-button size="small" @click="openRoles(row)">角色</el-button><el-button v-if="row.username!=='admin'" size="small" :type="row.status==='ENABLED'?'danger':'success'" @click="toggle(row)">{{row.status==='ENABLED'?'禁用':'启用'}}</el-button><el-button v-if="row.username!=='admin'" size="small" type="danger" @click="remove(row)">删除</el-button></template></el-table-column></el-table><el-pagination style="margin-top:14px;justify-content:flex-end" background layout="total,prev,pager,next" :total="total" v-model:current-page="query.page" @change="load"/></el-card>
  <el-dialog v-model="dialogVisible" :title="editingId?'编辑员工':'新增员工'" width="520px"><el-form ref="formRef" :model="form" :rules="rules" label-width="100px"><el-form-item label="用户名" prop="username"><el-input v-model="form.username" :disabled="!!editingId"/></el-form-item><el-form-item label="姓名" prop="realName"><el-input v-model="form.realName"/></el-form-item><el-form-item label="手机号"><el-input v-model="form.phone"/></el-form-item><el-form-item label="邮箱"><el-input v-model="form.email"/></el-form-item><el-form-item label="默认门店"><el-select v-model="form.defaultStoreId" clearable style="width:100%"><el-option v-for="s in stores" :key="s.id" :label="s.storeName" :value="s.id"/></el-select></el-form-item><el-form-item label="备注"><el-input v-model="form.remark" type="textarea"/></el-form-item></el-form><template #footer><el-button @click="dialogVisible=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog>
  <el-dialog v-model="roleVisible" title="分配角色" width="420px"><el-checkbox-group v-model="selectedRoles"><div v-for="r in roles" :key="r.id" style="margin:10px"><el-checkbox :value="r.id">{{r.roleName}}</el-checkbox></div></el-checkbox-group><template #footer><el-button @click="roleVisible=false">取消</el-button><el-button type="primary" @click="saveRoles">保存</el-button></template></el-dialog>
</div></template>
<script setup lang="ts">
import {onMounted,reactive,ref} from 'vue';import{ElMessage,ElMessageBox}from'element-plus';import{getUsers,createUser,updateUser,deleteUser,resetPassword,updateUserStatus,getUserRoles,assignUserRoles,getRoles}from'@/api';import{getStoreOptions}from'@/api/masterdata'
const loading=ref(false),rows=ref<any[]>([]),total=ref(0),stores=ref<any[]>([]),roles=ref<any[]>([]),dialogVisible=ref(false),roleVisible=ref(false),editingId=ref<number|null>(null),currentId=ref(0),selectedRoles=ref<number[]>([]),formRef=ref();const query=reactive({page:1,size:10,username:'',realName:'',status:''});const form=reactive<any>({username:'',realName:'',phone:'',email:'',defaultStoreId:null,remark:''});const rules={username:[{required:true,message:'请输入用户名',trigger:'blur'}],realName:[{required:true,message:'请输入姓名',trigger:'blur'}]}
onMounted(async()=>{await Promise.all([load(),loadOptions()])});async function load(){loading.value=true;try{const r=await getUsers(query);rows.value=r.data.records||[];total.value=r.data.total||0}finally{loading.value=false}}async function loadOptions(){const[s,r]=await Promise.all([getStoreOptions(),getRoles()]);stores.value=(s.data||[]).map((x:any)=>({id:x.value,storeName:x.label}));roles.value=r.data||[]}function storeName(id:number){return stores.value.find(s=>s.id===id)?.storeName||'-'}function openAdd(){editingId.value=null;Object.assign(form,{username:'',realName:'',phone:'',email:'',defaultStoreId:null,remark:''});dialogVisible.value=true}function openEdit(row:any){editingId.value=row.id;Object.assign(form,row);dialogVisible.value=true}async function save(){if(!await formRef.value.validate().catch(()=>false))return;editingId.value?await updateUser(editingId.value,form):await createUser(form);ElMessage.success('保存成功');dialogVisible.value=false;load()}async function reset(row:any){await ElMessageBox.confirm('密码将重置为 123456，确定吗？','确认',{type:'warning'});await resetPassword(row.id);ElMessage.success('密码已重置')}async function toggle(row:any){await updateUserStatus(row.id,row.status==='ENABLED'?'DISABLED':'ENABLED');ElMessage.success('状态已更新');load()}async function remove(row:any){await ElMessageBox.confirm('确定删除该员工吗？','确认',{type:'warning'});await deleteUser(row.id);ElMessage.success('删除成功');load()}async function openRoles(row:any){currentId.value=row.id;selectedRoles.value=(await getUserRoles(row.id)).data||[];roleVisible.value=true}async function saveRoles(){await assignUserRoles(currentId.value,selectedRoles.value);ElMessage.success('角色已保存');roleVisible.value=false}
</script>
