<template>
  <div class="document-page" v-loading="loading"><div class="document-header"><div><el-button link @click="router.push('/inventory/transfers')"><el-icon><ArrowLeft/></el-icon> 返回</el-button><h1>库存调拨详情</h1></div><div class="header-actions"><el-button v-if="detail?.status==='DRAFT'" type="primary" @click="approve">审核</el-button><el-button v-if="detail?.status==='APPROVED'" type="success" @click="complete">执行调拨</el-button><el-button v-if="detail&&['DRAFT','APPROVED'].includes(detail.status)" type="danger" plain @click="cancel">取消调拨</el-button></div></div>
    <el-card class="section-card"><template #header><div class="section-title"><span>调拨信息</span><el-tag :type="statusType(detail?.status)">{{statusLabel(detail?.status)}}</el-tag></div></template><el-descriptions v-if="detail" :column="3" border><el-descriptions-item label="调拨单号">{{detail.transferNo}}</el-descriptions-item><el-descriptions-item label="调拨日期">{{detail.transferDate}}</el-descriptions-item><el-descriptions-item label="调拨总数">{{detail.totalQuantity}}</el-descriptions-item><el-descriptions-item label="调出仓库">{{detail.fromWarehouseName}}</el-descriptions-item><el-descriptions-item label="调入仓库">{{detail.toWarehouseName}}</el-descriptions-item><el-descriptions-item label="备注">{{detail.remark||'-'}}</el-descriptions-item></el-descriptions></el-card>
    <el-card class="section-card"><template #header><div class="section-title"><span>调拨明细</span><small>共 {{detail?.items?.length||0}} 项商品</small></div></template><el-table :data="detail?.items||[]" border stripe><el-table-column type="index" label="序号" width="60" align="center"/><el-table-column prop="productCode" label="商品编码" width="140"/><el-table-column prop="productName" label="商品名称" min-width="190"/><el-table-column prop="specification" label="规格" min-width="120"/><el-table-column prop="unitName" label="单位" width="80"/><el-table-column prop="quantity" label="调拨数量" width="120" align="right"/><el-table-column prop="outboundQuantity" label="已调出" width="110" align="right"/><el-table-column prop="inboundQuantity" label="已调入" width="110" align="right"/><el-table-column prop="remark" label="备注" min-width="150"/></el-table></el-card>
  </div>
</template>
<script setup lang="ts">
import {onMounted,ref} from 'vue';import {useRoute,useRouter} from 'vue-router';import {ElMessage,ElMessageBox} from 'element-plus';import {approveInventoryTransfer,cancelInventoryTransfer,completeInventoryTransfer,getInventoryTransfer} from '@/api/inventory'
const route=useRoute();const router=useRouter();const id=Number(route.params.id);const loading=ref(false);const detail=ref<any>(null);onMounted(load);async function load(){loading.value=true;try{detail.value=(await getInventoryTransfer(id)).data}finally{loading.value=false}}function statusLabel(v:string){return({DRAFT:'草稿',APPROVED:'已审核',COMPLETED:'已完成',CANCELLED:'已取消'}as any)[v]||v}function statusType(v:string){return({DRAFT:'info',APPROVED:'warning',COMPLETED:'success',CANCELLED:'danger'}as any)[v]||''}async function approve(){await ElMessageBox.confirm('审核时将检查调出仓库存，是否继续？','审核调拨单',{type:'warning'});await approveInventoryTransfer(id);ElMessage.success('调拨单已审核');load()}async function complete(){await ElMessageBox.confirm('将扣减调出仓并增加调入仓库存，是否执行？','执行调拨',{type:'warning'});await completeInventoryTransfer(id);ElMessage.success('库存调拨完成');load()}async function cancel(){await ElMessageBox.confirm('确定取消该调拨单吗？','取消调拨',{type:'warning'});await cancelInventoryTransfer(id);ElMessage.success('调拨单已取消');load()}
</script>
<style scoped>.document-page{padding-bottom:24px}.document-header{min-height:66px;display:flex;align-items:center;justify-content:space-between;margin:-16px -20px 16px;padding:0 22px;background:#fff;border-bottom:1px solid #edf0f5}.document-header>div:first-child,.header-actions,.section-title{display:flex;align-items:center}.document-header>div:first-child{gap:14px}.document-header h1{margin:0;font-size:19px}.header-actions{gap:8px}.section-card+.section-card{margin-top:14px}.section-title{justify-content:space-between;gap:12px}.section-title span{font-size:16px;font-weight:600}.section-title small{color:#a1a8b3}</style>
