<template>
  <div class="document-page" v-loading="loading">
    <div class="document-header"><div><el-button link @click="router.back()"><el-icon><ArrowLeft/></el-icon> 返回</el-button><h1>新增库存调拨</h1></div><div class="header-actions"><el-button @click="router.push('/inventory/transfers')">取消</el-button><el-button type="primary" :loading="saving" @click="submit">保存草稿</el-button></div></div>
    <el-card class="section-card"><template #header><div class="section-title"><span>基本信息</span><small>同一仓库不能同时作为调出仓和调入仓</small></div></template><el-form ref="formRef" :model="form" :rules="rules" label-position="top"><el-row :gutter="20"><el-col :span="8"><el-form-item label="调拨日期" prop="transferDate"><el-date-picker v-model="form.transferDate" type="date" value-format="YYYY-MM-DD" style="width:100%"/></el-form-item></el-col><el-col :span="8"><el-form-item label="调出仓库" prop="fromWarehouseId"><el-select v-model="form.fromWarehouseId" style="width:100%" placeholder="选择调出仓库"><el-option v-for="item in warehouses" :key="item.value" :label="item.label" :value="item.value"/></el-select></el-form-item></el-col><el-col :span="8"><el-form-item label="调入仓库" prop="toWarehouseId"><el-select v-model="form.toWarehouseId" style="width:100%" placeholder="选择调入仓库"><el-option v-for="item in warehouses" :key="item.value" :label="item.label" :value="item.value" :disabled="item.value===form.fromWarehouseId"/></el-select></el-form-item></el-col><el-col :span="24"><el-form-item label="备注"><el-input v-model="form.remark" type="textarea" :rows="2" maxlength="500" show-word-limit/></el-form-item></el-col></el-row></el-form></el-card>
    <el-card class="section-card"><template #header><div class="detail-head"><div class="section-title"><span>调拨商品</span><small>可用库存随调出仓库变化</small></div><el-button type="primary" plain @click="addItem">+ 添加商品</el-button></div></template><el-table :data="form.items" border><el-table-column type="index" label="序号" width="60" align="center"/><el-table-column label="商品" min-width="260"><template #default="{row}"><el-select v-model="row.productId" filterable style="width:100%" placeholder="选择商品"><el-option v-for="item in products" :key="item.value" :value="item.value" :label="item.label"/></el-select></template></el-table-column><el-table-column label="可用库存" width="120" align="right"><template #default="{row}">{{ quantity(stockMap[row.productId]) }}</template></el-table-column><el-table-column label="调拨数量" width="180"><template #default="{row}"><el-input-number v-model="row.quantity" :min="0.0001" :precision="4" controls-position="right" style="width:150px"/></template></el-table-column><el-table-column label="备注" min-width="180"><template #default="{row}"><el-input v-model="row.remark" maxlength="500"/></template></el-table-column><el-table-column label="操作" width="75"><template #default="{$index}"><el-button link type="danger" @click="removeItem($index)">删除</el-button></template></el-table-column></el-table><el-empty v-if="!form.items.length" description="暂无商品，请点击右上角添加" :image-size="70"/><div class="summary"><span>商品种类：{{ form.items.length }}</span><strong>调拨总数：{{ totalQuantity }}</strong></div></el-card>
  </div>
</template>
<script setup lang="ts">
import { computed,onMounted,reactive,ref,watch } from 'vue';import { useRouter } from 'vue-router';import { ElMessage } from 'element-plus';import { createInventoryTransfer,getStocks } from '@/api/inventory';import { getProductOptions,getWarehouseOptions } from '@/api/masterdata'
const router=useRouter();const loading=ref(false);const saving=ref(false);const formRef=ref();const warehouses=ref<any[]>([]);const products=ref<any[]>([]);const stockMap=ref<Record<number,number>>({});const form=reactive<any>({transferDate:new Date().toISOString().slice(0,10),fromWarehouseId:null,toWarehouseId:null,remark:'',items:[]});const rules={transferDate:[{required:true,message:'请选择调拨日期',trigger:'change'}],fromWarehouseId:[{required:true,message:'请选择调出仓库',trigger:'change'}],toWarehouseId:[{required:true,message:'请选择调入仓库',trigger:'change'}]};const totalQuantity=computed(()=>quantity(form.items.reduce((s:number,i:any)=>s+Number(i.quantity||0),0)))
onMounted(async()=>{loading.value=true;try{const [w,p]=await Promise.all([getWarehouseOptions(),getProductOptions()]);warehouses.value=w.data||[];products.value=p.data||[];addItem()}finally{loading.value=false}})
watch(()=>form.fromWarehouseId,async warehouseId=>{stockMap.value={};if(!warehouseId)return;const r=await getStocks({page:1,size:1000,warehouseId});stockMap.value=Object.fromEntries((r.data.records||[]).map((s:any)=>[s.productId,Number(s.availableQuantity||0)]));if(form.toWarehouseId===warehouseId)form.toWarehouseId=null})
function quantity(v:any){return Number(v||0).toFixed(4).replace(/\.?0+$/,'')||'0'}function addItem(){form.items.push({productId:null,quantity:1,remark:''})}function removeItem(i:number){form.items.splice(i,1)}
async function submit(){if(!await formRef.value.validate().catch(()=>false))return;if(form.fromWarehouseId===form.toWarehouseId)return ElMessage.warning('调出仓库和调入仓库不能相同');if(!form.items.length||form.items.some((i:any)=>!i.productId||Number(i.quantity)<=0))return ElMessage.warning('请完整填写至少一条调拨商品');if(new Set(form.items.map((i:any)=>i.productId)).size!==form.items.length)return ElMessage.warning('同一商品不能重复添加');if(form.items.some((i:any)=>Number(i.quantity)>Number(stockMap.value[i.productId]||0)))return ElMessage.warning('调拨数量不能超过可用库存');saving.value=true;try{const r=await createInventoryTransfer(form);ElMessage.success('调拨单已保存');router.replace(`/inventory/transfers/${r.data.id}`)}finally{saving.value=false}}
</script>
<style scoped>.document-page{padding-bottom:24px}.document-header{min-height:66px;display:flex;align-items:center;justify-content:space-between;margin:-16px -20px 16px;padding:0 22px;background:#fff;border-bottom:1px solid #edf0f5}.document-header>div:first-child,.header-actions,.section-title,.detail-head,.summary{display:flex;align-items:center}.document-header>div:first-child{gap:14px}.document-header h1{margin:0;font-size:19px}.header-actions{gap:8px}.section-card+.section-card{margin-top:14px}.section-title{gap:12px}.section-title span{font-size:16px;font-weight:600}.section-title small{color:#a1a8b3}.detail-head{justify-content:space-between}.summary{justify-content:flex-end;gap:32px;margin-top:20px}.summary strong{font-size:17px;color:#e66b2f}</style>
