<template>
  <div class="page-wrapper">
    <el-card><div class="toolbar"><el-input v-model="query.transferNo" placeholder="调拨单号" clearable style="width:180px"/><el-select v-model="query.warehouseId" placeholder="调出/调入仓库" clearable style="width:180px"><el-option v-for="item in warehouses" :key="item.value" :label="item.label" :value="item.value"/></el-select><el-select v-model="query.status" placeholder="状态" clearable style="width:140px"><el-option v-for="item in statuses" :key="item.value" :label="item.label" :value="item.value"/></el-select><el-date-picker v-model="query.dateRange" type="daterange" range-separator="至" start-placeholder="开始日期" end-placeholder="结束日期" value-format="YYYY-MM-DD" style="width:260px"/><el-button type="primary" @click="fetchData">查询</el-button><el-button @click="resetQuery">重置</el-button><el-button type="success" @click="router.push('/inventory/transfers/new')">新增调拨</el-button></div></el-card>
    <el-card class="table-card"><el-table :data="tableData" v-loading="loading" border stripe><el-table-column prop="transferNo" label="调拨单号" width="180"/><el-table-column prop="transferDate" label="调拨日期" width="120"/><el-table-column prop="fromWarehouseName" label="调出仓库" min-width="150"/><el-table-column prop="toWarehouseName" label="调入仓库" min-width="150"/><el-table-column prop="totalQuantity" label="调拨总数" width="110" align="right"/><el-table-column label="状态" width="100"><template #default="{ row }"><el-tag :type="statusType(row.status)" size="small">{{ statusLabel(row.status) }}</el-tag></template></el-table-column><el-table-column prop="remark" label="备注" min-width="150" show-overflow-tooltip/><el-table-column label="操作" width="300" fixed="right"><template #default="{ row }"><el-button size="small" @click="router.push(`/inventory/transfers/${row.id}`)">查看</el-button><el-button v-if="row.status==='DRAFT'" size="small" type="primary" @click="approve(row)">审核</el-button><el-button v-if="row.status==='APPROVED'" size="small" type="success" @click="complete(row)">执行调拨</el-button><el-button v-if="['DRAFT','APPROVED'].includes(row.status)" size="small" type="danger" @click="cancel(row)">取消</el-button><el-button v-if="['DRAFT','CANCELLED'].includes(row.status)" size="small" type="danger" plain @click="remove(row)">删除</el-button></template></el-table-column></el-table><el-pagination class="pagination" background layout="total,prev,pager,next" :total="total" v-model:current-page="query.page" v-model:page-size="query.size" @change="fetchData"/></el-card>
  </div>
</template>
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'; import { useRouter } from 'vue-router'; import { ElMessage, ElMessageBox } from 'element-plus'; import { approveInventoryTransfer,cancelInventoryTransfer,completeInventoryTransfer,deleteInventoryTransfer,getInventoryTransfers } from '@/api/inventory'; import { getWarehouseOptions } from '@/api/masterdata'
const router=useRouter();const loading=ref(false);const tableData=ref<any[]>([]);const total=ref(0);const warehouses=ref<any[]>([]);const query=reactive({page:1,size:10,transferNo:'',warehouseId:'',status:'',dateRange:[] as string[]});const statuses=[{label:'草稿',value:'DRAFT'},{label:'已审核',value:'APPROVED'},{label:'已完成',value:'COMPLETED'},{label:'已取消',value:'CANCELLED'}]
onMounted(async()=>{warehouses.value=(await getWarehouseOptions()).data||[];fetchData()});function statusLabel(v:string){return statuses.find(i=>i.value===v)?.label||v}function statusType(v:string){return({DRAFT:'info',APPROVED:'warning',COMPLETED:'success',CANCELLED:'danger'} as any)[v]||''}
async function fetchData(){loading.value=true;try{const p:any={...query};if(p.dateRange?.length===2)[p.startDate,p.endDate]=p.dateRange;delete p.dateRange;const r=await getInventoryTransfers(p);tableData.value=r.data.records||[];total.value=r.data.total||0}finally{loading.value=false}}
function resetQuery(){Object.assign(query,{page:1,transferNo:'',warehouseId:'',status:'',dateRange:[]});fetchData()}
async function approve(row:any){await ElMessageBox.confirm('审核时将检查调出仓库存，是否继续？','审核调拨单',{type:'warning'});await approveInventoryTransfer(row.id);ElMessage.success('调拨单已审核');fetchData()}
async function complete(row:any){await ElMessageBox.confirm('将扣减调出仓并增加调入仓库存，是否执行？','执行调拨',{type:'warning'});await completeInventoryTransfer(row.id);ElMessage.success('库存调拨完成');fetchData()}
async function cancel(row:any){await ElMessageBox.confirm('确定取消该调拨单吗？','取消调拨',{type:'warning'});await cancelInventoryTransfer(row.id);ElMessage.success('调拨单已取消');fetchData()}
async function remove(row:any){await ElMessageBox.confirm('删除后无法恢复，是否继续？','删除调拨单',{type:'warning'});await deleteInventoryTransfer(row.id);ElMessage.success('调拨单已删除');fetchData()}
</script>
<style scoped>.toolbar{display:flex;gap:10px;flex-wrap:wrap}.table-card{margin-top:12px}.pagination{margin-top:12px;justify-content:flex-end}</style>
